spring.application.name=demo

# Habilita inserções em lote no Hibernate
spring.jpa.properties.hibernate.jdbc.batch_size=100

# Ordena os inserts para otimizar a compilação do lote no banco
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Desabilita a exibição de SQL no console (MUITO IMPORTANTE)
# Se isso ficar true, printar 25.000 linhas de SQL vai travar sua IDE/Terminal
spring.jpa.show-sql=false

jwt.secret=f4557958a67b9bb9b762f1e0a7054c53dbe2af8c4cbafb730e8b60a3e4079192
jwt.expiration=86400000

spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:testdb