spring.application.name=demo

# Habilita inserções em lote no Hibernate
spring.jpa.properties.hibernate.jdbc.batch_size=100

# Ordena os inserts para otimizar a compilação do lote no banco
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# Desabilita a exibição de SQL no console (MUITO IMPORTANTE)
# Se isso ficar true, printar 25.000 linhas de SQL vai travar sua IDE/Terminal
spring.jpa.show-sql=false